### ISSUE TITLE
sos

### ISSUE THREAD

**Issue by coco66688** [CherryWaffle/LavaLink-Node-Monitor-for-Discord#1]
File "ready.js" has loaded successfully!
(node:235) UnhandledPromiseRejectionWarning: Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (/home/runner/LavaLink-Node-Monitor-for-Discord/node_modules/discord.js/src/client/websocket/WebSocketManager.js:258:15)
(node:235) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:235) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by CherryWaffle** [comment]
You Gotta Allow Intents
